/* ─────────────────────────────────────────────────────────
   오프라인 컨셉 템플릿 50종
   학습 메커닉 축 기반 — 한국 학생용
   ───────────────────────────────────────────────────────── */

import type { Concept, PostitColor } from '../../types';

export type Mechanic =
  | 'ability'   // 능력 획득
  | 'stealth'   // 스텔스
  | 'puzzle'    // 퍼즐
  | 'combat'    // 전투
  | 'exploration' // 탐험
  | 'survival'  // 생존/자원
  | 'narrative'; // 내러티브/감정

export interface SeedPostit {
  text: string;
  color: PostitColor;
  tags?: string[];
}

export interface ConceptTemplate {
  id: string;
  title: string;
  mechanic: Mechanic;
  genres: string[];        // 장르 태그
  concept: Concept;
  seedPostits: SeedPostit[];
}

export const MECHANIC_LABEL: Record<Mechanic, string> = {
  ability:     '능력 획득',
  stealth:     '스텔스',
  puzzle:      '퍼즐',
  combat:      '전투',
  exploration: '탐험',
  survival:    '생존·자원',
  narrative:   '내러티브',
};

export const MECHANIC_COLOR: Record<Mechanic, string> = {
  ability:     'var(--ochre)',
  stealth:     'var(--ink-700)',
  puzzle:      'var(--blueprint)',
  combat:      'var(--brick)',
  exploration: 'var(--moss)',
  survival:    'var(--brick-deep)',
  narrative:   'var(--blueprint-deep)',
};

/* ─────────────────────────────────────────────────────────
   50종 템플릿
   ───────────────────────────────────────────────────────── */

export const TEMPLATES: ConceptTemplate[] = [
  // ─── 능력 획득 (8) ───
  {
    id: 'abl-01-dash-temple',
    title: '대시를 얻는 잊혀진 사원',
    mechanic: 'ability',
    genres: ['3D 액션 어드벤처'],
    concept: {
      theme: '고대 정글에 묻힌 사원',
      intent: '플레이어가 대시 능력을 획득하고, 그 사용법을 환경에서 학습한 뒤 보스에서 시험한다',
      coreMechanic: '대시(짧은 무적 이동)',
      learningGoals: ['대시의 거리감각', '대시 타이밍', '대시로 적을 회피하는 패턴'],
      pacing: '잔잔한 진입 → 짧은 전투 → 대시 획득 → 연습 구간 → 보스',
    },
    seedPostits: [
      { text: '입구 — 보물이 보이지만 절벽으로 가로막힌 풍경', color: 'mint', tags: ['vista'] },
      { text: '초보 적 2-3마리와의 첫 전투', color: 'pink', tags: ['combat'] },
      { text: '대시 능력 제단 (시각적으로 화려한 룸)', color: 'yellow', tags: ['reward'] },
      { text: '얕은 함정 2개를 대시로 넘는 연습실', color: 'blue', tags: ['teach'] },
      { text: '대시에 약한 신규 적 — "관성을 가진" 적', color: 'pink', tags: ['combat'] },
      { text: '보스: 좌우 대시 회피가 필수인 패턴', color: 'pink', tags: ['boss'] },
      { text: '보스 직후 일방통행 게이트 — 입구로 못 돌아감', color: 'lilac', tags: ['flow'] },
    ],
  },
  {
    id: 'abl-02-doublejump-cathedral',
    title: '더블점프를 얻는 폐허 대성당',
    mechanic: 'ability',
    genres: ['3D 플랫포머', '3D 액션 어드벤처'],
    concept: {
      theme: '천장이 무너진 거대 대성당',
      intent: '수직 공간을 통해 더블점프의 가치를 즉시 체감시킨다',
      coreMechanic: '더블점프',
      learningGoals: ['수직 거리 판단', '공중 입력 타이밍', '낙하 후 복귀'],
      pacing: '협소한 진입 → 수직 개방감 → 능력 획득 → 거대한 시험장',
    },
    seedPostits: [
      { text: '좁은 회랑 — 천장이 점점 높아짐', color: 'yellow', tags: ['anticipation'] },
      { text: '거대한 부서진 종 (랜드마크)', color: 'mint', tags: ['vista'] },
      { text: '도달 불가능한 발코니에 빛나는 오브젝트', color: 'yellow', tags: ['promise'] },
      { text: '아래로 떨어지면 다시 올라와야 하는 1회용 추락 룸', color: 'pink', tags: ['risk'] },
      { text: '더블점프 능력 — 스테인드글라스 빛 속에서', color: 'lilac', tags: ['reward'] },
      { text: '수직 통과 챔버 — 5단 발판', color: 'blue', tags: ['teach'] },
      { text: '천장 보스: 위에서 떨어지는 패턴', color: 'pink', tags: ['boss'] },
    ],
  },
  {
    id: 'abl-03-grapple-canyon',
    title: '갈고리 능력을 얻는 협곡 유적',
    mechanic: 'ability',
    genres: ['3D 액션 어드벤처'],
    concept: {
      theme: '바람 부는 사막 협곡 사이의 부유 유적',
      intent: '수평 이동의 자유를 갈고리로 확장',
      coreMechanic: '갈고리 (지정 노드로 견인)',
      learningGoals: ['시야에서 갈고리 포인트 찾기', '진자 운동 응용', '연속 갈고리'],
      pacing: '느린 등반 → 갈고리 획득 → 빠른 회복 → 보스 추격',
    },
    seedPostits: [
      { text: '입구 다리 (반쯤 무너짐) — 강제로 우회', color: 'blue' },
      { text: '바람 효과음 강한 외부 구역', color: 'mint', tags: ['mood'] },
      { text: '갈고리 제단 (지진으로 통로 열림 연출)', color: 'yellow', tags: ['reward'] },
      { text: '갈고리 포인트가 4개 보이는 개방 챔버', color: 'blue', tags: ['teach'] },
      { text: '추락 시 보호망 (낮은 좌절감)', color: 'mint', tags: ['safety'] },
      { text: '보스: 갈고리로 약점에 접근해야 하는 비행 적', color: 'pink', tags: ['boss'] },
    ],
  },
  {
    id: 'abl-04-wallclimb-crypt',
    title: '벽타기를 얻는 지하 묘소',
    mechanic: 'ability',
    genres: ['3D 닌자 액션', '3D 클라이밍'],
    concept: {
      theme: '낮은 천장의 좁은 묘실들',
      intent: '벽타기로 가로/세로 모두를 자유롭게 만든다',
      coreMechanic: '벽타기 (잠시 벽에 붙음)',
      learningGoals: ['벽 점프 거리', '벽-벽 점프 체인', '지구력 게이지 관리'],
      pacing: '폐쇄 → 능력 획득 → 개방 → 미로 보스',
    },
    seedPostits: [
      { text: '낮은 천장 회랑 — 횃불 ASMR', color: 'lilac', tags: ['mood'] },
      { text: '몸을 굽혀 통과해야 하는 좁은 통로', color: 'blue' },
      { text: '벽타기 두루마리 (작은 보상감)', color: 'yellow', tags: ['reward'] },
      { text: '벽-벽 점프 3회 챔버', color: 'blue', tags: ['teach'] },
      { text: '거미형 적 — 천장에 매달림', color: 'pink', tags: ['enemy'] },
      { text: '보스: 사면이 벽인 정사각형 챔버', color: 'pink', tags: ['boss'] },
    ],
  },
  {
    id: 'abl-05-firebreath-volcano',
    title: '불을 뿜는 능력을 얻는 화산',
    mechanic: 'ability',
    genres: ['3D 액션 RPG', '판타지'],
    concept: {
      theme: '활동 중인 화산 내부',
      intent: '환경 자체가 능력의 시각적 메타포',
      coreMechanic: '단발 화염 브레스',
      learningGoals: ['거리 판단', '연료 게이지', '얼음 적 약점'],
      pacing: '강렬한 진입 → 약한 적 → 능력 획득 → 얼음 영역 → 화염 보스',
    },
    seedPostits: [
      { text: '용암이 흐르는 외부 다리 (긴장)', color: 'pink', tags: ['mood'] },
      { text: '얼음 결정으로 막힌 첫 진로', color: 'blue', tags: ['gate'] },
      { text: '화염 정수 제단', color: 'yellow', tags: ['reward'] },
      { text: '얼음 적 4-5마리가 있는 시험실', color: 'pink', tags: ['practice'] },
      { text: '연료가 부족한 채로 진입하는 좁은 통로', color: 'lilac', tags: ['tension'] },
      { text: '얼음 정령 보스 — 환경이 결정으로 채워짐', color: 'pink', tags: ['boss'] },
    ],
  },
  {
    id: 'abl-06-timeslow-clocktower',
    title: '시간 감속을 얻는 시계탑',
    mechanic: 'ability',
    genres: ['3D 액션 퍼즐'],
    concept: {
      theme: '거대 톱니바퀴들이 움직이는 시계탑',
      intent: '시간 감속을 통해 환경 퍼즐과 전투를 동시에 변형',
      coreMechanic: '주변 시간을 1/4로 감속 (자원형)',
      learningGoals: ['감속 토글 타이밍', '게이지 관리', '환경 활용'],
      pacing: '관찰 → 능력 → 작은 응용 → 큰 응용 → 보스',
    },
    seedPostits: [
      { text: '거대 진자 룸 (1초마다 스쳐감)', color: 'mint', tags: ['vista'] },
      { text: '톱니바퀴 사이를 빠져 나가는 구간', color: 'blue', tags: ['teach'] },
      { text: '시계공의 책 (능력 획득 텍스트 비트)', color: 'yellow', tags: ['reward'] },
      { text: '날아오는 화살을 감속 후 회피하는 챔버', color: 'pink', tags: ['practice'] },
      { text: '게이지 부족 위기 — 환경 보충 아이템', color: 'lilac' },
      { text: '시간을 멈출 수 있는 보스 (역으로)', color: 'pink', tags: ['boss'] },
    ],
  },
  {
    id: 'abl-07-water-flooded-keep',
    title: '잠수 능력을 얻는 침수 요새',
    mechanic: 'ability',
    genres: ['3D 액션 어드벤처'],
    concept: {
      theme: '반쯤 침수된 해안 요새',
      intent: '수평 공간을 수직-수중으로 확장',
      coreMechanic: '잠수 / 산소 게이지',
      learningGoals: ['산소 관리', '수중 시야', '환경 함정 회피'],
      pacing: '지상 탐험 → 잠수 능력 → 수중 미로 → 거대 수중 보스',
    },
    seedPostits: [
      { text: '말라가는 우물 (트로피 연출)', color: 'mint' },
      { text: '물 깊이가 점점 늘어나는 통로', color: 'blue', tags: ['progression'] },
      { text: '심해 비전 — 산호초 룸', color: 'yellow', tags: ['reward'] },
      { text: '산소 부족 시 시야 흐려짐 학습실', color: 'lilac' },
      { text: '수중 회피 가능한 가시 함정', color: 'pink' },
      { text: '거대 해양 생물 보스', color: 'pink', tags: ['boss'] },
    ],
  },
  {
    id: 'abl-08-shadow-spire',
    title: '그림자 통과 능력을 얻는 첨탑',
    mechanic: 'ability',
    genres: ['3D 액션 어드벤처'],
    concept: {
      theme: '햇빛과 그림자가 교차하는 첨탑 외벽',
      intent: '빛/그림자 이원성을 능력으로 직접 표현',
      coreMechanic: '그림자에 들어가면 무적·통과 가능',
      learningGoals: ['그림자 경로 읽기', '햇빛 회피', '시간대 변화 응용'],
      pacing: '햇빛 노출 → 능력 획득 → 그림자 활용 → 종합 보스',
    },
    seedPostits: [
      { text: '드리운 그림자가 움직이는 회랑', color: 'lilac', tags: ['mood'] },
      { text: '닫힌 셔터 (햇빛을 막아 그림자 만듦)', color: 'blue', tags: ['env'] },
      { text: '그림자의 정수 — 어두운 제단', color: 'yellow', tags: ['reward'] },
      { text: '그림자만으로 가로지르는 회전 룸', color: 'blue', tags: ['teach'] },
      { text: '햇빛을 쏘는 시계 적', color: 'pink', tags: ['enemy'] },
      { text: '햇빛과 그림자를 모두 다루는 보스', color: 'pink', tags: ['boss'] },
    ],
  },

  // ─── 스텔스 (6) ───
  {
    id: 'ste-01-manor-heist',
    title: '귀족 저택 잠입',
    mechanic: 'stealth',
    genres: ['3D 스텔스', '느와르'],
    concept: {
      theme: '연회가 한창인 18세기 귀족 저택',
      intent: '발각 시 즉사 패널티 대신 추격으로 페이스 변화',
      coreMechanic: '엄폐, 발소리, 시야 콘 회피',
      learningGoals: ['시야 콘 읽기', '소리 영역', '디스트랙션 도구'],
      pacing: '느린 관찰 → 진입 → 핵심 절도 → 추격 탈출',
    },
    seedPostits: [
      { text: '정문 — 경비 두 명 (관찰만 가능)', color: 'blue' },
      { text: '연회장 발코니 (전체 조감)', color: 'mint', tags: ['vista'] },
      { text: '주방 — 디스트랙션용 접시', color: 'yellow', tags: ['tool'] },
      { text: '서재 — 핵심 절도 목표', color: 'pink', tags: ['goal'] },
      { text: '비밀 통로 (정원으로)', color: 'lilac', tags: ['escape'] },
      { text: '경보 발동 시 잠긴 문 — 우회 필요', color: 'pink' },
    ],
  },
  {
    id: 'ste-02-warehouse-job',
    title: '항구 창고의 한 시간',
    mechanic: 'stealth',
    genres: ['3D 스텔스', '현대 액션'],
    concept: {
      theme: '비 오는 밤, 화물선 옆 창고',
      intent: '시간 제약과 패트롤 로테이션',
      coreMechanic: '엄폐, 순찰 패턴 암기',
      learningGoals: ['시간 관리', '루트 계획', '백업 출구'],
      pacing: '관찰 → 침투 → 데드라인 압박 → 탈출',
    },
    seedPostits: [
      { text: '컨테이너 미로 (입구)', color: 'blue' },
      { text: '감시카메라 사각 — 5초 윈도우', color: 'lilac' },
      { text: '감독관 사무실 (핵심 정보)', color: 'pink', tags: ['goal'] },
      { text: '경비견 — 후각 메커닉', color: 'pink', tags: ['enemy'] },
      { text: '지붕 위 탈출 경로 (예비)', color: 'mint', tags: ['escape'] },
    ],
  },
  {
    id: 'ste-03-castle-spy',
    title: '적국 성의 첩보 임무',
    mechanic: 'stealth',
    genres: ['3D 스텔스', '판타지'],
    concept: {
      theme: '석조 성의 어두운 회랑',
      intent: '횃불 점멸과 그림자가 핵심 자원',
      coreMechanic: '횃불 끄기, 그림자 이용',
      learningGoals: ['시야 차단', '복귀 경로', '소리 위장'],
      pacing: '진입 → 정보 수집 3건 → 위치 노출 → 비밀 탈출',
    },
    seedPostits: [
      { text: '벽 사이 비밀 통로 입구', color: 'lilac' },
      { text: '횃불을 끄면 어두워지는 회의실', color: 'blue', tags: ['env'] },
      { text: '왕의 침소 — 결정적 문서', color: 'pink', tags: ['goal'] },
      { text: '교대 시간 — 5분 윈도우', color: 'yellow', tags: ['timing'] },
    ],
  },
  {
    id: 'ste-04-spacefacility',
    title: '폐쇄된 우주 시설 잠입',
    mechanic: 'stealth',
    genres: ['3D SF 스텔스'],
    concept: {
      theme: '비상등만 켜진 우주 정거장',
      intent: '센서·드론 적과 환경 활용',
      coreMechanic: 'EMP 던지기, 환기구 이동',
      learningGoals: ['센서 회피', '환기구 맵 읽기', '소음 관리'],
      pacing: '에어록 진입 → 데이터 코어 → 자폭 카운트다운 탈출',
    },
    seedPostits: [
      { text: '에어록 (시작 — 5초 압력 조정)', color: 'blue' },
      { text: '환기구 분기점 — 3방향 선택', color: 'lilac', tags: ['choice'] },
      { text: '드론 패트롤 — 적외선 시야', color: 'pink', tags: ['enemy'] },
      { text: '데이터 코어 룸 — 30초 다운로드', color: 'pink', tags: ['goal'] },
      { text: '자폭 시퀀스 — 카운트다운 탈출', color: 'pink', tags: ['climax'] },
    ],
  },
  {
    id: 'ste-05-temple-thief',
    title: '신전의 도둑',
    mechanic: 'stealth',
    genres: ['3D 액션 스텔스', '판타지'],
    concept: {
      theme: '계단식 사원의 보물 회랑',
      intent: '환경 함정과 함정 작동기 협업',
      coreMechanic: '엄폐, 함정 회피, 트리거 절단',
      learningGoals: ['함정 패턴', '루트 사전 검사', '비상 우회'],
      pacing: '진입 → 작은 보물 → 함정 작동 → 중앙 보물 → 탈출',
    },
    seedPostits: [
      { text: '연꽃 정원 (시작 — 평화로움)', color: 'mint' },
      { text: '바닥 압력판 — 화살 함정', color: 'pink', tags: ['trap'] },
      { text: '진자 칼날 회랑', color: 'pink', tags: ['trap'] },
      { text: '중앙 우상 — 핵심 보물', color: 'pink', tags: ['goal'] },
      { text: '추격 — 무너지는 천장', color: 'pink', tags: ['climax'] },
    ],
  },
  {
    id: 'ste-06-prison-break',
    title: '감옥 탈출',
    mechanic: 'stealth',
    genres: ['3D 스텔스 드라마'],
    concept: {
      theme: '낡은 석조 감옥',
      intent: '제약(무기 없음)에서 시작하는 점진적 권능 확장',
      coreMechanic: '소음 위장, 자원 절도',
      learningGoals: ['패트롤 암기', '도구 조합', '동료 협력'],
      pacing: '독방 → 식당 → 작업장 → 비밀 터널 → 외벽',
    },
    seedPostits: [
      { text: '독방 (시작 — 도구 0개)', color: 'blue' },
      { text: '식당 — 숟가락 절도', color: 'yellow', tags: ['tool'] },
      { text: '작업장 — 줄/끌', color: 'yellow', tags: ['tool'] },
      { text: '비밀 터널 입구 (벽 뒤)', color: 'lilac', tags: ['secret'] },
      { text: '외벽 — 서치라이트', color: 'pink', tags: ['climax'] },
    ],
  },

  // ─── 퍼즐 (8) ───
  {
    id: 'puz-01-mirror-tower',
    title: '거울 빛 굴절 탑',
    mechanic: 'puzzle',
    genres: ['3D 퍼즐 어드벤처'],
    concept: {
      theme: '거대 거울들이 회전하는 탑',
      intent: '빛 굴절 메커닉을 한 가지 룰로 5번 변주',
      coreMechanic: '거울 회전·이동으로 빛줄기 라우팅',
      learningGoals: ['각도 계산', '중간 목표 설정', '여러 거울 조합'],
      pacing: '단순 → 응용 → 시간 제한 → 다중 목표 → 보스',
    },
    seedPostits: [
      { text: '튜토리얼 룸 — 거울 1개', color: 'blue', tags: ['teach'] },
      { text: '거울 2개로 두 목표 동시 점화', color: 'blue' },
      { text: '회전 받침대 — 움직이는 목표', color: 'pink', tags: ['time'] },
      { text: '거대 만화경 룸 (압권)', color: 'mint', tags: ['vista'] },
      { text: '보스: 사방에 거울이 있는 환경', color: 'pink', tags: ['boss'] },
    ],
  },
  {
    id: 'puz-02-water-pumping',
    title: '수로의 수위 퍼즐 던전',
    mechanic: 'puzzle',
    genres: ['3D 액션 퍼즐'],
    concept: {
      theme: '지하 수로망',
      intent: '수위 변화로 같은 공간이 다른 레이아웃이 됨',
      coreMechanic: '수문 개폐로 수위 조절',
      learningGoals: ['공간 재해석', '의도된 순서', '되돌리기 사고'],
      pacing: '낮은 수위 → 중간 수위 → 높은 수위 → 모두 활용',
    },
    seedPostits: [
      { text: '수문 A — 동쪽 수위 올림', color: 'blue', tags: ['mechanism'] },
      { text: '수문 B — 서쪽 수위 내림', color: 'blue', tags: ['mechanism'] },
      { text: '수면 위에서만 통과 가능한 동굴', color: 'pink' },
      { text: '수면 아래에서만 보이는 비밀', color: 'lilac', tags: ['secret'] },
      { text: '중앙 챔버 — 모든 수위가 필요', color: 'pink', tags: ['climax'] },
    ],
  },
  {
    id: 'puz-03-magnetic-cave',
    title: '자기장 동굴',
    mechanic: 'puzzle',
    genres: ['3D SF 퍼즐'],
    concept: {
      theme: '자성 광물이 빛나는 동굴',
      intent: '극성 N/S 한 가지 룰의 깊은 변주',
      coreMechanic: '플레이어 극성 토글, 자성 오브젝트 인력/척력',
      learningGoals: ['극성 결과 예측', '오브젝트 연쇄 이동', '환경 함정 응용'],
      pacing: '진입 → 학습 4단계 → 응용 → 보스',
    },
    seedPostits: [
      { text: '극성 학습실 — 큐브 1개 끌어오기', color: 'blue', tags: ['teach'] },
      { text: '두 큐브 동시 정렬 퍼즐', color: 'blue' },
      { text: '극성 함정 — 자성 가시', color: 'pink' },
      { text: '거대 금속 문 (인력으로 열기)', color: 'pink', tags: ['gate'] },
      { text: '자성 보스 — 환경 활용', color: 'pink', tags: ['boss'] },
    ],
  },
  {
    id: 'puz-04-clock-mechanism',
    title: '시계 톱니 던전',
    mechanic: 'puzzle',
    genres: ['3D 스팀펑크 퍼즐'],
    concept: {
      theme: '거대 시계 내부',
      intent: '회전·타이밍 동기화 퍼즐',
      coreMechanic: '톱니 속도 조절, 진자 타이밍',
      learningGoals: ['주기 읽기', '동기화', '예측 사고'],
      pacing: '느린 진자 → 빠른 진자 → 다중 진자 → 보스',
    },
    seedPostits: [
      { text: '느린 진자 1개 회피 룸', color: 'blue', tags: ['teach'] },
      { text: '진자 2개 동기화', color: 'blue' },
      { text: '톱니 위에서 점프하는 구간', color: 'pink' },
      { text: '메인 시계 페이스 (랜드마크)', color: 'mint', tags: ['vista'] },
      { text: '시간 보스 — 시침/분침 패턴', color: 'pink', tags: ['boss'] },
    ],
  },
  {
    id: 'puz-05-mushroom-forest',
    title: '거대 버섯 숲의 식물 퍼즐',
    mechanic: 'puzzle',
    genres: ['3D 퍼즐 어드벤처'],
    concept: {
      theme: '바이오 발광 버섯이 가득한 숲',
      intent: '식물 성장 메커닉으로 환경 자체를 변형',
      coreMechanic: '씨앗 심기 → 버섯 성장 → 발판/통로',
      learningGoals: ['배치 사고', '자원 관리', '되돌리기 불가의 무게'],
      pacing: '학습 → 응용 → 시간 압박 → 종합 챔버',
    },
    seedPostits: [
      { text: '씨앗 1개 심기 → 발판 생성', color: 'blue', tags: ['teach'] },
      { text: '높이 조절 — 큰 버섯/작은 버섯', color: 'blue' },
      { text: '시간 안에 자라지 않으면 사라짐', color: 'pink' },
      { text: '거대 부모 버섯 (랜드마크)', color: 'mint', tags: ['vista'] },
      { text: '뿌리 정령 보스', color: 'pink', tags: ['boss'] },
    ],
  },
  {
    id: 'puz-06-ice-sliding',
    title: '얼음 미끄럼 던전',
    mechanic: 'puzzle',
    genres: ['3D 퍼즐'],
    concept: {
      theme: '얼어붙은 동굴 호수',
      intent: '클래식 슬라이딩 퍼즐을 공간적 어휘로',
      coreMechanic: '얼음판 위에서는 멈출 수 없음',
      learningGoals: ['경로 사전 계획', '벽 활용', '도구 사용'],
      pacing: '단순 슬라이드 → 분기 → 다단계 → 보스',
    },
    seedPostits: [
      { text: '직선 슬라이드 학습', color: 'blue', tags: ['teach'] },
      { text: '벽에 부딪혀 방향 전환', color: 'blue' },
      { text: '구멍 → 추락 → 우회', color: 'pink' },
      { text: '얼음판 위 키 + 자물쇠 문', color: 'yellow', tags: ['key'] },
      { text: '얼음 보스 — 미끄러지며 회피', color: 'pink', tags: ['boss'] },
    ],
  },
  {
    id: 'puz-07-mirror-maze-asylum',
    title: '거울 미로 정신병원',
    mechanic: 'puzzle',
    genres: ['3D 심리 호러'],
    concept: {
      theme: '버려진 정신병원의 거울 미로',
      intent: '공간 인지 자체를 퍼즐의 일부로',
      coreMechanic: '거울 너머가 진짜 통로인지 분별',
      learningGoals: ['패턴 인식', '오감 의심', '낙인 표시 활용'],
      pacing: '신뢰 → 배신 → 학습 → 통제',
    },
    seedPostits: [
      { text: '첫 거울 룸 (실수 가능)', color: 'lilac', tags: ['mood'] },
      { text: '벽에 그어진 분필 표시 (단서)', color: 'yellow', tags: ['clue'] },
      { text: '깨진 거울 — 잠시 진실 노출', color: 'lilac' },
      { text: '동일해 보이지만 다른 룸들', color: 'pink' },
      { text: '거울 속 자아 보스', color: 'pink', tags: ['boss'] },
    ],
  },
  {
    id: 'puz-08-block-pushing-pyramid',
    title: '블록 밀기 피라미드',
    mechanic: 'puzzle',
    genres: ['3D 퍼즐'],
    concept: {
      theme: '계단식 피라미드 내부',
      intent: '클래식 소코반 메커닉의 공간적 확장',
      coreMechanic: '석조 블록 밀기 (당기기 X)',
      learningGoals: ['되돌릴 수 없는 사고', '단계 계획', '키 + 자물쇠'],
      pacing: '단일 블록 → 다중 블록 → 시간 압박 → 보스',
    },
    seedPostits: [
      { text: '블록 1개 → 압력판', color: 'blue', tags: ['teach'] },
      { text: '블록 3개 → 다중 압력판', color: 'blue' },
      { text: '실수하면 잠기는 잠금문', color: 'pink', tags: ['risk'] },
      { text: '왕의 무덤 — 핵심 챔버', color: 'mint', tags: ['vista'] },
      { text: '석상 보스 — 블록 패턴 활용', color: 'pink', tags: ['boss'] },
    ],
  },

  // ─── 전투 (8) ───
  {
    id: 'cmb-01-arena-coliseum',
    title: '검투장 콜로세움',
    mechanic: 'combat',
    genres: ['3D 액션 아레나'],
    concept: {
      theme: '관중이 가득한 고대 검투장',
      intent: '웨이브 기반 전투 — 매 웨이브 새 메커닉 소개',
      coreMechanic: '근접 전투, 무기 픽업',
      learningGoals: ['적 우선순위', '환경 무기', '회복 타이밍'],
      pacing: '솔로 → 듀얼 → 무리 → 보스 → 결승',
    },
    seedPostits: [
      { text: '대기실 (긴장 빌드업)', color: 'mint', tags: ['mood'] },
      { text: '아레나 진입 (관중 함성)', color: 'pink', tags: ['mood'] },
      { text: '웨이브 1: 단일 검사', color: 'pink' },
      { text: '웨이브 2: 궁수 + 방패병', color: 'pink' },
      { text: '환경 무기 — 함정 작동기', color: 'yellow' },
      { text: '보스: 챔피언 검투사', color: 'pink', tags: ['boss'] },
    ],
  },
  {
    id: 'cmb-02-defense-village',
    title: '마을 방어전',
    mechanic: 'combat',
    genres: ['3D 액션 전략'],
    concept: {
      theme: '안개 낀 강가 마을',
      intent: '시간이 핵심 자원 — 준비/방어/추격 3단계',
      coreMechanic: '함정 설치, 동선 통제',
      learningGoals: ['공간 통제', '자원 분배', '우선 위협 판단'],
      pacing: '낮(준비) → 황혼(파동) → 밤(전면전) → 새벽(추격)',
    },
    seedPostits: [
      { text: '중앙 우물 — 거점', color: 'mint', tags: ['hub'] },
      { text: '동쪽 다리 — 함정 포인트', color: 'yellow', tags: ['choke'] },
      { text: '서쪽 숲 — 매복 가능 지역', color: 'lilac' },
      { text: '북쪽 언덕 — 궁수 배치', color: 'blue', tags: ['vantage'] },
      { text: '족장 보스 — 새벽 출현', color: 'pink', tags: ['boss'] },
    ],
  },
  {
    id: 'cmb-03-corridor-shooter',
    title: '복도식 슈터 임무',
    mechanic: 'combat',
    genres: ['3D FPS'],
    concept: {
      theme: '버려진 군사 시설',
      intent: '엄폐 기반 총격전, 무기 유형 4종 회전',
      coreMechanic: '엄폐 사격, 수류탄',
      learningGoals: ['엄폐 활용', '재장전 타이밍', '무기 교체'],
      pacing: '진입 → 룸 클리어 × 3 → 후퇴전 → 보스',
    },
    seedPostits: [
      { text: '입구 — 정찰병 2명', color: 'pink' },
      { text: '대형 사무실 — 엄폐 다수', color: 'pink' },
      { text: '좁은 복도 — 산탄총 유리', color: 'pink' },
      { text: '폭발물 박스 (환경 활용)', color: 'yellow' },
      { text: '미니건 사수 보스', color: 'pink', tags: ['boss'] },
    ],
  },
  {
    id: 'cmb-04-boss-rush-temple',
    title: '신들의 보스 러시',
    mechanic: 'combat',
    genres: ['3D 액션', '판타지'],
    concept: {
      theme: '신들의 성소 — 짧은 회랑과 거대 챔버 교차',
      intent: '연속 보스 4종, 회복 통제',
      coreMechanic: '회피 굴림, 패턴 학습',
      learningGoals: ['텔리그래프 읽기', '회복 분배', '메모리'],
      pacing: '소회복 → 보스 → 회복 → 보스 → 회복 → 최종',
    },
    seedPostits: [
      { text: '회복 회랑 (잠시 안전)', color: 'mint', tags: ['rest'] },
      { text: '보스 1: 화염 거인', color: 'pink', tags: ['boss'] },
      { text: '보스 2: 그림자 쌍둥이', color: 'pink', tags: ['boss'] },
      { text: '보스 3: 바람의 매', color: 'pink', tags: ['boss'] },
      { text: '최종 보스: 합체 형태', color: 'pink', tags: ['climax'] },
    ],
  },
  {
    id: 'cmb-05-vehicle-chase',
    title: '차량 추격 시퀀스',
    mechanic: 'combat',
    genres: ['3D 액션 레이싱'],
    concept: {
      theme: '비 오는 고속도로',
      intent: '이동하면서 전투 — 정적 공간을 동적으로',
      coreMechanic: '운전 + 사격',
      learningGoals: ['멀티태스킹', '환경 위협', '엄폐 이동'],
      pacing: '도시 진입 → 추격 → 헬기 합류 → 보스 차량 → 종착',
    },
    seedPostits: [
      { text: '시작 신호 (탈출 차량)', color: 'mint' },
      { text: '경찰차 패트롤 3대', color: 'pink' },
      { text: '터널 — 짧은 안전', color: 'lilac' },
      { text: '헬기 합류 — 위에서 압박', color: 'pink' },
      { text: '보스 — 장갑 SUV', color: 'pink', tags: ['boss'] },
    ],
  },
  {
    id: 'cmb-06-naval-boarding',
    title: '해상 함선 보딩',
    mechanic: 'combat',
    genres: ['3D 액션 어드벤처', '해적'],
    concept: {
      theme: '폭풍우 속 적함의 갑판',
      intent: '비좁은 공간에서의 다층 전투',
      coreMechanic: '검과 권총, 갑판 등반',
      learningGoals: ['공간 활용', '환경 위협', '입체 이동'],
      pacing: '상갑판 → 돛대 위 → 하갑판 → 함장실',
    },
    seedPostits: [
      { text: '갑판 진입 — 일제 사격', color: 'pink' },
      { text: '돛대 위 저격수', color: 'pink' },
      { text: '뱃밥 (위로 점프)', color: 'yellow' },
      { text: '하갑판 — 좁은 어둠', color: 'lilac' },
      { text: '함장 보스 — 함장실', color: 'pink', tags: ['boss'] },
    ],
  },
  {
    id: 'cmb-07-mech-factory',
    title: '메카 공장 침투전',
    mechanic: 'combat',
    genres: ['3D SF 액션'],
    concept: {
      theme: '거대 로봇을 제조하는 공장',
      intent: '컨베이어/프레스 환경이 곧 전장',
      coreMechanic: '환경 위협 활용 + 전투',
      learningGoals: ['타이밍', '위치 선정', '환경 트리거'],
      pacing: '진입 → 조립 라인 → 보안 강화 → 거대 메카 보스',
    },
    seedPostits: [
      { text: '컨베이어 벨트 진입', color: 'blue' },
      { text: '프레스 함정 (환경 무기)', color: 'pink' },
      { text: '용접 로봇 적', color: 'pink' },
      { text: '검수 챔버 — 잠시 안전', color: 'mint', tags: ['rest'] },
      { text: '거대 메카 보스 (조립 미완)', color: 'pink', tags: ['boss'] },
    ],
  },
  {
    id: 'cmb-08-soulslike-bridge',
    title: '소울라이크 다리 위 격투',
    mechanic: 'combat',
    genres: ['3D 소울라이크 액션 RPG'],
    concept: {
      theme: '안개 협곡 위의 좁은 석조 다리',
      intent: '단 하나의 다리 위에서 정밀 전투',
      coreMechanic: '스태미나, 패링, 굴림',
      learningGoals: ['패링 타이밍', '회복 약 사용', '재시도'],
      pacing: '튜토리얼 적 → 정예 → 미니보스 → 최종',
    },
    seedPostits: [
      { text: '안개 다리 입구 (랜드마크)', color: 'mint', tags: ['vista'] },
      { text: '약한 적 2-3 — 워밍업', color: 'pink' },
      { text: '엘리트 검사 — 패링 필수', color: 'pink' },
      { text: '회복 화톳불', color: 'yellow', tags: ['rest'] },
      { text: '대형 기사 보스', color: 'pink', tags: ['boss'] },
    ],
  },

  // ─── 탐험 (8) ───
  {
    id: 'exp-01-open-cove',
    title: '열린 해안 만 탐험',
    mechanic: 'exploration',
    genres: ['3D 오픈월드 어드벤처'],
    concept: {
      theme: '여러 작은 섬과 해안',
      intent: '비선형 탐험 — 플레이어가 순서를 정함',
      coreMechanic: '관찰 → 시도 → 발견',
      learningGoals: ['랜드마크 인지', '재방문', '자가 정렬'],
      pacing: '광활 → 호기심 추적 → 발견 누적',
    },
    seedPostits: [
      { text: '중앙 해안 (허브)', color: 'mint', tags: ['hub'] },
      { text: '북쪽 등대 — 시야 트임', color: 'blue', tags: ['vantage'] },
      { text: '서쪽 난파선 — 보물', color: 'yellow' },
      { text: '남쪽 동굴 — 닫힌 문 (재방문)', color: 'lilac' },
      { text: '동쪽 절벽 — 도전 보상', color: 'yellow' },
    ],
  },
  {
    id: 'exp-02-vertical-canyon',
    title: '수직 협곡 도시',
    mechanic: 'exploration',
    genres: ['3D 탐험 어드벤처'],
    concept: {
      theme: '협곡 절벽에 매달린 도시',
      intent: '수직 탐험 — 위/아래 모두 발견 보상',
      coreMechanic: '클라이밍 + 활공',
      learningGoals: ['수직 사고', '체력 자원', '대안 경로'],
      pacing: '최하층 → 중층 등반 → 정상 → 비행 하강',
    },
    seedPostits: [
      { text: '최하층 시장 (시작)', color: 'mint' },
      { text: '중간층 다리망', color: 'blue' },
      { text: '상층 신전 (목표)', color: 'pink', tags: ['goal'] },
      { text: '비밀 굴 — 측면', color: 'lilac', tags: ['secret'] },
      { text: '활공 종착 — 새 시작점', color: 'mint' },
    ],
  },
  {
    id: 'exp-03-ruins-island',
    title: '신비의 유적 섬',
    mechanic: 'exploration',
    genres: ['3D 탐험 어드벤처', '리얼리즘'],
    concept: {
      theme: '무인도의 고대 문명 유적',
      intent: '환경 스토리텔링 중심',
      coreMechanic: '관찰, 단서 조합',
      learningGoals: ['세계관 읽기', '인내', '추론'],
      pacing: '도착 → 흩어진 단서 → 중앙 비밀 → 떠남',
    },
    seedPostits: [
      { text: '해변 도착 (정착)', color: 'mint' },
      { text: '돌비석 — 첫 단서', color: 'yellow', tags: ['clue'] },
      { text: '벽화 — 잃어버린 종족', color: 'yellow', tags: ['lore'] },
      { text: '중앙 신전 — 잠긴 입구', color: 'lilac', tags: ['gate'] },
      { text: '내부 비밀 — 결말', color: 'pink', tags: ['climax'] },
    ],
  },
  {
    id: 'exp-04-cosmic-anomaly',
    title: '우주 이상점 탐사',
    mechanic: 'exploration',
    genres: ['3D SF 탐험'],
    concept: {
      theme: '외계 행성의 비현실적 이상점',
      intent: '비현실 공간 — 물리 법칙 변형',
      coreMechanic: '중력 변화, 시간 왜곡 관찰',
      learningGoals: ['공간 적응', '안전 영역 식별', '대담함'],
      pacing: '착륙 → 적응 → 핵심 발견 → 탈출',
    },
    seedPostits: [
      { text: '착륙 지점 (베이스)', color: 'mint', tags: ['hub'] },
      { text: '중력 역전 구역', color: 'lilac' },
      { text: '시간 느린 호수', color: 'lilac' },
      { text: '이상점 핵심 (랜드마크)', color: 'mint', tags: ['vista'] },
      { text: '탈출 카운트다운', color: 'pink', tags: ['climax'] },
    ],
  },
  {
    id: 'exp-05-foggy-village',
    title: '안개 마을의 진실',
    mechanic: 'exploration',
    genres: ['3D 심리 호러 탐험'],
    concept: {
      theme: '시간이 멈춘 듯한 안개 마을',
      intent: '느린 탐험으로 분위기 누적',
      coreMechanic: '관찰, 메모 수집',
      learningGoals: ['집중', '서사 조립', '용기'],
      pacing: '도착 → 의문 → 깊은 곳 → 진실',
    },
    seedPostits: [
      { text: '마을 입구 (안개)', color: 'lilac', tags: ['mood'] },
      { text: '교회 — 멈춘 시계', color: 'mint', tags: ['vista'] },
      { text: '도서관 — 마지막 일지', color: 'yellow', tags: ['clue'] },
      { text: '지하 — 진실의 방', color: 'pink', tags: ['climax'] },
    ],
  },
  {
    id: 'exp-06-deep-forest',
    title: '깊은 숲의 영적 여행',
    mechanic: 'exploration',
    genres: ['3D 판타지 탐험'],
    concept: {
      theme: '거대 고목들의 숲',
      intent: '비선형, 영적 보상',
      coreMechanic: '관찰, 정령 대화',
      learningGoals: ['느린 탐험', '환경 읽기', '존중'],
      pacing: '진입 → 4 정령 → 중앙 신성목 → 변화',
    },
    seedPostits: [
      { text: '숲 입구 — 빛 줄기', color: 'mint' },
      { text: '바람의 정령 (북)', color: 'lilac' },
      { text: '강의 정령 (남)', color: 'lilac' },
      { text: '땅의 정령 (동)', color: 'lilac' },
      { text: '신성목 (중앙)', color: 'mint', tags: ['vista'] },
    ],
  },
  {
    id: 'exp-07-haunted-mansion',
    title: '대저택 미스터리',
    mechanic: 'exploration',
    genres: ['3D 미스터리 어드벤처'],
    concept: {
      theme: '폐쇄된 빅토리아 대저택',
      intent: '방마다 단서, 자물쇠는 다른 방에',
      coreMechanic: '관찰, 키 수집, 일기 조합',
      learningGoals: ['공간 기억', '비선형 사고', '인내'],
      pacing: '입구 → 1층 둘러보기 → 2층 → 지하실',
    },
    seedPostits: [
      { text: '입구 홀 — 큰 계단', color: 'mint', tags: ['hub'] },
      { text: '서재 — 다이어리 1권', color: 'yellow', tags: ['clue'] },
      { text: '식당 — 열쇠 1', color: 'yellow', tags: ['key'] },
      { text: '주인 침실 — 잠긴 금고', color: 'lilac' },
      { text: '지하실 — 진실', color: 'pink', tags: ['climax'] },
    ],
  },
  {
    id: 'exp-08-sky-archipelago',
    title: '하늘 군도 비행 탐험',
    mechanic: 'exploration',
    genres: ['3D 판타지 탐험'],
    concept: {
      theme: '하늘에 떠 있는 섬들의 군도',
      intent: '플레이어 자유 진행, 시각적 발견 중심',
      coreMechanic: '비행 / 활공',
      learningGoals: ['공간 인지', '대담함', '비밀 탐색'],
      pacing: '베이스 → 자유 탐험 → 핵심 섬 발견',
    },
    seedPostits: [
      { text: '베이스 섬 — 마을', color: 'mint', tags: ['hub'] },
      { text: '북쪽 폭풍 섬', color: 'lilac' },
      { text: '동쪽 사원 섬', color: 'yellow' },
      { text: '남쪽 잊혀진 거탑', color: 'pink' },
      { text: '중앙 비밀 — 구름 속', color: 'pink', tags: ['climax'] },
    ],
  },

  // ─── 생존·자원 (6) ───
  {
    id: 'sur-01-blizzard-base',
    title: '눈보라 속 기지 생존',
    mechanic: 'survival',
    genres: ['3D 생존 드라마'],
    concept: {
      theme: '북극의 고립된 연구 기지',
      intent: '추위/연료/식량 3축 관리',
      coreMechanic: '자원 채집과 배분',
      learningGoals: ['우선순위', '위험 평가', '장기 계획'],
      pacing: '평온 → 첫 위기 → 자원 고갈 → 구조 신호',
    },
    seedPostits: [
      { text: '기지 (허브)', color: 'mint', tags: ['hub'] },
      { text: '연료 창고 (서쪽)', color: 'yellow' },
      { text: '식량 저장고 (동쪽)', color: 'yellow' },
      { text: '눈보라 — 외출 제한', color: 'pink', tags: ['event'] },
      { text: '구조 신호 송신 — 클라이맥스', color: 'pink', tags: ['climax'] },
    ],
  },
  {
    id: 'sur-02-desert-caravan',
    title: '사막 캐러밴',
    mechanic: 'survival',
    genres: ['3D 생존'],
    concept: {
      theme: '광활한 사막을 가로지르는 여정',
      intent: '물/그늘/체력 관리',
      coreMechanic: '오아시스 라우팅',
      learningGoals: ['루트 선택', '자원 분배', '동료 관리'],
      pacing: '출발 → 첫 오아시스 → 모래폭풍 → 목적지',
    },
    seedPostits: [
      { text: '출발지 (도시)', color: 'mint' },
      { text: '오아시스 1', color: 'yellow' },
      { text: '모래폭풍 (이벤트)', color: 'pink' },
      { text: '버려진 캐러밴 (단서)', color: 'lilac' },
      { text: '목적지 도시', color: 'mint', tags: ['climax'] },
    ],
  },
  {
    id: 'sur-03-zombie-mall',
    title: '쇼핑몰의 좀비 농성',
    mechanic: 'survival',
    genres: ['3D 호러 생존'],
    concept: {
      theme: '폐쇄된 대형 쇼핑몰',
      intent: '공간 통제와 자원 채집의 교차',
      coreMechanic: '바리케이드, 자원, 소음 관리',
      learningGoals: ['공간 보호', '소음 절제', '동료 협업'],
      pacing: '진입 → 거점 확보 → 외부 임무 → 마지막 밤',
    },
    seedPostits: [
      { text: '푸드코트 (허브)', color: 'mint', tags: ['hub'] },
      { text: '약국 — 의료품', color: 'yellow' },
      { text: '주차장 — 위험 + 차량', color: 'pink' },
      { text: '서점 — 안전 + 책', color: 'mint' },
      { text: '옥상 헬리포트 (탈출)', color: 'mint', tags: ['climax'] },
    ],
  },
  {
    id: 'sur-04-island-castaway',
    title: '무인도 표류',
    mechanic: 'survival',
    genres: ['3D 생존'],
    concept: {
      theme: '열대 무인도',
      intent: '0에서 시작해 점진적 능력 확장',
      coreMechanic: '제작, 식량, 도구',
      learningGoals: ['우선순위', '실험 정신', '장기 사고'],
      pacing: '표류 → 거주지 → 도구 → 구조 시도',
    },
    seedPostits: [
      { text: '해변 도착 — 잔해', color: 'mint' },
      { text: '담수 시내 (필수)', color: 'yellow' },
      { text: '코코넛 숲', color: 'yellow' },
      { text: '뗏목 제작장', color: 'pink', tags: ['goal'] },
      { text: '바다로 출발 (탈출)', color: 'mint', tags: ['climax'] },
    ],
  },
  {
    id: 'sur-05-plague-village',
    title: '역병 마을 의무관',
    mechanic: 'survival',
    genres: ['3D 생존 드라마'],
    concept: {
      theme: '역병이 도는 중세 마을',
      intent: '한정된 의약품으로 누구를 살릴지 선택',
      coreMechanic: '치료 자원 분배',
      learningGoals: ['윤리 판단', '리소스 분배', '결과 수용'],
      pacing: '도착 → 환자 발견 → 자원 결핍 → 선택',
    },
    seedPostits: [
      { text: '교회 (베이스)', color: 'mint' },
      { text: '대장간 — 일가족 감염', color: 'pink' },
      { text: '식료품점 — 노인', color: 'pink' },
      { text: '약초 숲 — 마지막 자원', color: 'yellow' },
      { text: '결말 — 누가 살았나', color: 'lilac', tags: ['climax'] },
    ],
  },
  {
    id: 'sur-06-cave-trapped',
    title: '동굴 매몰 탈출',
    mechanic: 'survival',
    genres: ['3D 생존 서스펜스'],
    concept: {
      theme: '광산 사고 후 매몰된 갱도',
      intent: '산소·빛·체력 동시 관리',
      coreMechanic: '횃불, 산소, 채굴',
      learningGoals: ['자원 동시 관리', '위험 평가', '결단'],
      pacing: '사고 → 길 찾기 → 동료 구조 → 탈출',
    },
    seedPostits: [
      { text: '매몰 직후 (시작)', color: 'lilac' },
      { text: '동료 발견 — 부상', color: 'pink' },
      { text: '환기구 — 산소 + 빛', color: 'yellow' },
      { text: '갱도 분기 (선택)', color: 'lilac' },
      { text: '지표 빛 — 탈출', color: 'mint', tags: ['climax'] },
    ],
  },

  // ─── 내러티브 (6) ───
  {
    id: 'nar-01-childhood-home',
    title: '돌아온 어린 시절 집',
    mechanic: 'narrative',
    genres: ['3D 내러티브'],
    concept: {
      theme: '오랜만에 방문한 부모님 집',
      intent: '공간이 곧 기억의 트리거',
      coreMechanic: '오브젝트 상호작용으로 회상',
      learningGoals: ['감정 누적', '비선형 이야기', '대답 없는 질문'],
      pacing: '도착 → 둘러보기 → 핵심 방 → 떠남',
    },
    seedPostits: [
      { text: '현관 — 첫 회상', color: 'mint' },
      { text: '거실 — 가족 사진', color: 'lilac' },
      { text: '내 방 — 일기장', color: 'lilac' },
      { text: '부엌 — 어머니의 흔적', color: 'pink' },
      { text: '결말 — 다시 떠남', color: 'lilac', tags: ['climax'] },
    ],
  },
  {
    id: 'nar-02-train-journey',
    title: '국경을 넘는 열차',
    mechanic: 'narrative',
    genres: ['내러티브', '드라마'],
    concept: {
      theme: '여러 칸의 야간 열차',
      intent: '제한된 공간 내 다양한 인물',
      coreMechanic: '대화 선택, 관계 변화',
      learningGoals: ['공감', '관찰', '선택 결과'],
      pacing: '출발 → 만남 → 위기 → 도착',
    },
    seedPostits: [
      { text: '내 객실 (시작)', color: 'mint' },
      { text: '식당칸 — 노인', color: 'lilac' },
      { text: '복도 — 의문의 여인', color: 'pink' },
      { text: '기관실 — 비밀', color: 'lilac' },
      { text: '국경역 — 결말', color: 'pink', tags: ['climax'] },
    ],
  },
  {
    id: 'nar-03-deathbed-recollection',
    title: '임종의 회상',
    mechanic: 'narrative',
    genres: ['내러티브', '드라마'],
    concept: {
      theme: '병실과 회상 공간의 교차',
      intent: '플레이어가 인생의 챕터를 골라 재방문',
      coreMechanic: '챕터 선택, 환경 변화',
      learningGoals: ['비선형 시간', '결정 무게', '용서'],
      pacing: '현재 → 청년 → 중년 → 노년 → 현재',
    },
    seedPostits: [
      { text: '병실 (허브)', color: 'lilac', tags: ['hub'] },
      { text: '청년기 — 첫 사랑', color: 'pink' },
      { text: '중년기 — 일과 가족', color: 'mint' },
      { text: '노년기 — 후회', color: 'lilac' },
      { text: '결말 — 평화', color: 'mint', tags: ['climax'] },
    ],
  },
  {
    id: 'nar-04-letters-from-front',
    title: '전선에서 온 편지',
    mechanic: 'narrative',
    genres: ['내러티브', '전쟁 드라마'],
    concept: {
      theme: '집과 전선 두 공간의 평행',
      intent: '같은 사건의 두 시각',
      coreMechanic: '편지 읽기, 공간 전환',
      learningGoals: ['이중 관점', '환경 변화', '시간 축'],
      pacing: '집 → 전선 → 집 → 전선 → 진실',
    },
    seedPostits: [
      { text: '집 부엌 — 첫 편지', color: 'mint' },
      { text: '참호 — 발신 장면', color: 'pink' },
      { text: '집 침실 — 두 번째 편지', color: 'lilac' },
      { text: '병원 — 마지막 편지', color: 'lilac' },
      { text: '결말 — 도착', color: 'pink', tags: ['climax'] },
    ],
  },
  {
    id: 'nar-05-island-festival',
    title: '섬 마을 축제의 하루',
    mechanic: 'narrative',
    genres: ['내러티브', '슬라이스 오브 라이프'],
    concept: {
      theme: '여름 섬 마을',
      intent: '느린 하루, 작은 사건들',
      coreMechanic: '돌아다니기, 대화',
      learningGoals: ['관찰', '소소함', '따뜻함'],
      pacing: '아침 → 점심 → 저녁 축제 → 밤하늘',
    },
    seedPostits: [
      { text: '아침 시장', color: 'mint' },
      { text: '바닷가 청년들', color: 'mint' },
      { text: '점심 — 할머니 가게', color: 'yellow' },
      { text: '저녁 축제 광장', color: 'pink', tags: ['climax'] },
      { text: '밤 — 폭죽', color: 'lilac' },
    ],
  },
  {
    id: 'nar-06-final-conversation',
    title: '마지막 대화',
    mechanic: 'narrative',
    genres: ['3D 내러티브'],
    concept: {
      theme: '카페 한 곳에서의 대화',
      intent: '하나의 공간, 깊은 선택',
      coreMechanic: '대화 분기',
      learningGoals: ['미세 표현', '선택 누적', '결과 수용'],
      pacing: '도착 → 가벼움 → 진실 → 결정 → 헤어짐',
    },
    seedPostits: [
      { text: '카페 입구', color: 'mint' },
      { text: '주문 — 첫 인사', color: 'mint' },
      { text: '본론 — 진실 1', color: 'pink' },
      { text: '갈등 — 진실 2', color: 'pink' },
      { text: '결말 — 떠남', color: 'lilac', tags: ['climax'] },
    ],
  },
];

export const byMechanic = (m: Mechanic) => TEMPLATES.filter((t) => t.mechanic === m);

export const MECHANIC_GROUPS: Array<{ mechanic: Mechanic; label: string }> = [
  { mechanic: 'ability',     label: '능력 획득' },
  { mechanic: 'stealth',     label: '스텔스' },
  { mechanic: 'puzzle',      label: '퍼즐' },
  { mechanic: 'combat',      label: '전투' },
  { mechanic: 'exploration', label: '탐험' },
  { mechanic: 'survival',    label: '생존·자원' },
  { mechanic: 'narrative',   label: '내러티브' },
];
